### ISSUE TITLE
Same keyboard shortcut for selection quotes and brackets contents

### ISSUE THREAD

**Issue by smjure** [Pustelto/Bracketeer#33] opened 2020-03-22 05:59 UTC
Similarly as in issue #30, it would be great to be able to define one keybinding for selection of the content between quotes and brackets. 

Thank you for the great job.

**Comment by Pustelto** [comment] 2020-07-29 20:21
Closing since it's duplicate of #30 as you mentions @smjure. So for any related info or comments please watch this issue. Don't have much time for Bracketeer right now so not sure how fast I can get it done.

**Closed by Pustelto** 2020-07-29 20:21 UTC
